apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ (StructuralData .TargetLabelKey)}}: {{.TargetLabelValue}}
    # this is dynamically generated and used for group deployment and deletion tracking
    {{ (StructuralData .TargetDeploymentLabelKey)}}: {{.TargetDeploymentLabelValue}}
  name: {{.TargetName}}
  namespace: {{.TargetNamespace}}
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      {{ (StructuralData .TargetLabelKey)}}: {{.TargetLabelValue}}
      {{ (StructuralData .TargetDeploymentLabelKey)}}: {{.TargetDeploymentLabelValue}}
  template:
    metadata:
      labels:
        {{ (StructuralData .TargetLabelKey)}}: {{.TargetLabelValue}}
        {{ (StructuralData .TargetDeploymentLabelKey)}}: {{.TargetDeploymentLabelValue}}
    spec:
      nodeSelector:
        slo: "true"
      containers:
      - image: acnpublic.azurecr.io/sanamsarath/h2playground:0.3
        name: nginx
        ports:
        - containerPort: {{.TargetPort}}
        resources:
          requests:
            cpu: "15m"
            memory: "30Mi"
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900
      - key: "slo"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"