---
# Source: dra-example-driver/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dra-example-driver-service-account
  namespace: {{.Namespace}}
  labels:
    helm.sh/chart: dra-example-driver-0.1.3
    app.kubernetes.io/name: dra-example-driver
    app.kubernetes.io/instance: dra-example-driver
    app.kubernetes.io/version: "v0.1.0"
