apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Name}}
  labels:
    group: baseline-job
    job-type: long-running
spec:
  parallelism: {{.Replicas}}
  completions: {{.Replicas}}
  completionMode: {{.Mode}}
  activeDeadlineSeconds: 86400   # 24 h
  template:
    metadata:
      labels:
        group: baseline-pod
        job-type: long-running
    spec:
      restartPolicy: Never
      containers:
      - name: {{.Name}}
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
        args: ["{{.Sleep}}"]
        resources:
          requests:
            cpu: "{{.CPUMilli}}m"
            memory: "{{.Memory}}"